// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"home":{"path":"home","id":"home"}},
    routeComponents: {
'home': React.lazy(() => import(/* webpackChunkName: "p__home" */'../../pages/home.tsx')),
},
  };
}
